services:
    tinypng.request_listener:
        class: Tinypng\Bundle\EventListener\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }
        calls:
            - [setContainer, ["@service_container"]]